#!/usr/bin/env bash
#
# Generate Kubernetes ConfigMap(s) for CloudNativePG SQL init scripts
# This script reads SQL migration files and generates ConfigMaps that CloudNativePG
# can use to initialize the database schema on first startup.
#
# Features:
#   - Automatically splits into multiple ConfigMaps if size exceeds safe limit
#   - Kubernetes ConfigMap limit: 1MB, safe limit used: 800KB
#   - Maintains migration order across ConfigMaps
#   - One SQL file per ConfigMap key for clarity
#   - Size tracking and warnings to stderr
#
# Example output:
#   ================================================
#   SQL ConfigMap Generator
#   ================================================
#   SQL files found: 2
#   Total SQL size: 39KB
#   Estimated YAML size: 51KB
#   ConfigMaps required: 1
#   Size limit per ConfigMap: 819KB
#   ================================================
#
#   Migration: 001_install.sql (size: 15KB)
#   Migration: 002_install_models.sql (size: 24KB)
#
#   ✓ Generation complete!
#     Files processed: 2
#     ConfigMaps generated: 1
#   ================================================
#
# Usage:
#   ./manifests/generate-sql-configmap.sh > manifests/application/rem-api/postgres-init-configmap.yaml
#
# CloudNativePG Reference:
#   bootstrap.initdb.postInitApplicationSQLRefs.configMapRefs
#   https://cloudnative-pg.io/documentation/current/bootstrap/

set -euo pipefail

# Configuration
SQL_DIR="rem/sql/migrations"
CONFIGMAP_NAME="rem-postgres-init-sql"
NAMESPACE="rem-api"

# Size limits (in bytes)
# Kubernetes ConfigMap max: 1048576 (1MB)
# Safe limit (80% of max to account for YAML overhead): 838860 (~819KB)
MAX_CONFIGMAP_SIZE=838860
WARN_SIZE=$((MAX_CONFIGMAP_SIZE * 70 / 100))  # Warn at 70% (~573KB)

# Validate SQL directory exists
if [[ ! -d "$SQL_DIR" ]]; then
  echo "Error: SQL directory not found: $SQL_DIR" >&2
  exit 1
fi

# Find all SQL files in order
mapfile -t SQL_FILES < <(find "$SQL_DIR" -name "*.sql" | sort)

if [[ ${#SQL_FILES[@]} -eq 0 ]]; then
  echo "Error: No SQL files found in $SQL_DIR" >&2
  exit 1
fi

# Function to get file size
get_file_size() {
  wc -c < "$1"
}

# Function to generate ConfigMap header
generate_header() {
  local cm_index=$1
  local cm_suffix=""
  if [[ $cm_index -gt 0 ]]; then
    cm_suffix="-$((cm_index + 1))"
  fi

  cat <<EOF
# Generated by: manifests/generate-sql-configmap.sh
# Date: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Source: $SQL_DIR
# ConfigMap: $((cm_index + 1)) of ${total_configmaps}
#
# This ConfigMap contains SQL initialization scripts for CloudNativePG.
# Referenced in postgres-cluster.yaml via bootstrap.initdb.postInitApplicationSQLRefs
#
# DO NOT EDIT MANUALLY - Regenerate with:
#   ./manifests/generate-sql-configmap.sh > manifests/application/rem-api/postgres-init-configmap.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CONFIGMAP_NAME}${cm_suffix}
  namespace: $NAMESPACE
  labels:
    app: rem-postgres
    component: database
    managed-by: kustomize
    migration-batch: "$((cm_index + 1))"
data:
EOF
}

# Function to add SQL file to output
add_sql_file() {
  local sql_file=$1
  local filename=$(basename "$sql_file")
  local file_size=$(get_file_size "$sql_file")

  echo "  # Migration: $filename (size: $((file_size / 1024))KB)" >&2
  echo "  $filename: |"
  # Indent SQL file contents (2 spaces for YAML data block)
  sed 's/^/    /' "$sql_file"
  echo ""
}

# Calculate total size and determine if we need multiple ConfigMaps
total_size=0
for sql_file in "${SQL_FILES[@]}"; do
  file_size=$(get_file_size "$sql_file")
  total_size=$((total_size + file_size))
done

# Estimate YAML overhead (headers, indentation, etc.) - roughly 30% overhead
yaml_overhead=$((total_size * 30 / 100))
estimated_total=$((total_size + yaml_overhead))

# Calculate number of ConfigMaps needed
total_configmaps=1
if [[ $estimated_total -gt $MAX_CONFIGMAP_SIZE ]]; then
  total_configmaps=$(((estimated_total + MAX_CONFIGMAP_SIZE - 1) / MAX_CONFIGMAP_SIZE))
fi

# Emit warnings to stderr
echo "================================================" >&2
echo "SQL ConfigMap Generator" >&2
echo "================================================" >&2
echo "SQL files found: ${#SQL_FILES[@]}" >&2
echo "Total SQL size: $((total_size / 1024))KB" >&2
echo "Estimated YAML size: $((estimated_total / 1024))KB" >&2
echo "ConfigMaps required: $total_configmaps" >&2
echo "Size limit per ConfigMap: $((MAX_CONFIGMAP_SIZE / 1024))KB" >&2

if [[ $estimated_total -gt $WARN_SIZE ]] && [[ $estimated_total -lt $MAX_CONFIGMAP_SIZE ]]; then
  echo "" >&2
  echo "⚠️  WARNING: Approaching ConfigMap size limit!" >&2
  echo "   Current: $((estimated_total / 1024))KB" >&2
  echo "   Limit: $((MAX_CONFIGMAP_SIZE / 1024))KB" >&2
  echo "   Consider splitting migrations or using external storage." >&2
fi

echo "================================================" >&2
echo "" >&2

# Generate ConfigMap(s)
current_cm_index=0
current_cm_size=0
files_in_current_cm=0

# Generate first ConfigMap header
generate_header $current_cm_index

for sql_file in "${SQL_FILES[@]}"; do
  file_size=$(get_file_size "$sql_file")
  # Estimate YAML size (file + indentation + metadata)
  yaml_size=$((file_size + file_size * 20 / 100))

  # Check if adding this file would exceed limit
  if [[ $files_in_current_cm -gt 0 ]] && [[ $((current_cm_size + yaml_size)) -gt $MAX_CONFIGMAP_SIZE ]]; then
    # Close current ConfigMap and start new one
    echo "---"
    current_cm_index=$((current_cm_index + 1))
    current_cm_size=0
    files_in_current_cm=0
    echo "" >&2
    echo "Starting ConfigMap $((current_cm_index + 1))..." >&2
    generate_header $current_cm_index
  fi

  # Add file to current ConfigMap
  add_sql_file "$sql_file"
  current_cm_size=$((current_cm_size + yaml_size))
  files_in_current_cm=$((files_in_current_cm + 1))
done

# Generate footer with usage instructions
cat <<'EOF'
---
# Usage in postgres-cluster.yaml:
#
# spec:
#   bootstrap:
#     initdb:
#       database: remdb
#       owner: remuser
#       postInitApplicationSQLRefs:
#         configMapRefs:
#           # If multiple ConfigMaps generated, reference all in order:
#           - name: rem-postgres-init-sql
#             key: 001_install.sql
#           - name: rem-postgres-init-sql
#             key: 002_install_models.sql
#           # If split across ConfigMaps:
#           # - name: rem-postgres-init-sql-2
#           #   key: 003_large_migration.sql
#
# Notes:
# - Scripts execute in the order specified
# - Runs once during cluster bootstrap (first startup)
# - Idempotent: Uses IF NOT EXISTS, CREATE OR REPLACE, etc.
# - Errors will fail the bootstrap process
# - ConfigMap size limit: 1MB (script uses 800KB safe limit)
# - Large migrations are automatically split across multiple ConfigMaps
EOF

echo "" >&2
echo "✓ Generation complete!" >&2
echo "  Files processed: ${#SQL_FILES[@]}" >&2
echo "  ConfigMaps generated: $((current_cm_index + 1))" >&2
echo "================================================" >&2
